# Generated by Django 6.1.1 on 2026-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blinket',
            fields=[
                ('CustomerName', models.CharField(max_length=10)),
                ('Products', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('Orders', models.CharField(max_length=10)),
                ('Payment', models.FloatField()),
                ('Details', models.TextField()),
            ],
        ),
    ]
